<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="doc" nsURI="http://srg.aut.uah.es/micobs/doctpl/doc" nsPrefix="doctpl">
  <eClassifiers xsi:type="ecore:EClass" name="DDocument" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocuments" upperBound="-1"
        eType="#//DApplicableDocument" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocuments" upperBound="-1"
        eType="#//DApplicableDocument" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="figures" upperBound="-1"
        eType="#//DAbstractFigure" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//DAbstractTable" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractRelatedDocument" abstract="true"
      eSuperTypes="#//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refDocument" lowerBound="1"
        eType="#//DDocument" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DApplicableDocument" eSuperTypes="#//DAbstractRelatedDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//DDocument" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DReferenceDocument" eSuperTypes="#//DAbstractRelatedDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//DDocument" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractFigure" abstract="true" eSuperTypes="#//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//DDocument" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DFigure" abstract="true" eSuperTypes="#//DAbstractFigure"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractTable" abstract="true" eSuperTypes="#//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//DDocument" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTableFromPicture" abstract="true" eSuperTypes="#//DAbstractTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTable" abstract="true" eSuperTypes="#//DAbstractTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//DRow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//DColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//DCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DCell" eSuperTypes="#//DParagraph"/>
  <eClassifiers xsi:type="ecore:EClass" name="DParagraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" upperBound="-1" eType="#//DText"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//DReferenceableObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DReferenceableObject"/>
</ecore:EPackage>
