<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="doc" nsURI="http://srg.aut.uah.es/micobs/doctpl/doc" nsPrefix="doctpl">
  <eClassifiers xsi:type="ecore:EClass" name="DDocumentTemplate" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocuments" upperBound="-1"
        eType="#//DApplicableDocument" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocuments" upperBound="-1"
        eType="#//DApplicableDocument" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="figures" upperBound="-1"
        eType="#//DAbstractFigure" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//DAbstractTable" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//DAbstractSection" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractRelatedDocument" abstract="true"
      eSuperTypes="#//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refDocument" lowerBound="1"
        eType="#//DDocumentTemplate" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DApplicableDocument" eSuperTypes="#//DAbstractRelatedDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//DDocumentTemplate" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DReferenceDocument" eSuperTypes="#//DAbstractRelatedDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//DDocumentTemplate" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractFigure" abstract="true" eSuperTypes="#//DBodyContent #//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//DDocumentTemplate" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DFigure" abstract="true" eSuperTypes="#//DAbstractFigure"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractTable" abstract="true" eSuperTypes="#//DBodyContent #//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//DDocumentTemplate" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DPictureAsTable" abstract="true" eSuperTypes="#//DAbstractTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBasicTable" abstract="true" eSuperTypes="#//DAbstractTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" lowerBound="1" upperBound="-1"
        eType="#//DRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="span" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" lowerBound="1"
        upperBound="-1" eType="#//DColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="span" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" lowerBound="1" upperBound="-1"
        eType="#//DCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DCell" eSuperTypes="#//DBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsections" upperBound="-1"
        eType="#//DAbstractSection" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//DDocumentTemplate" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DFixedSection" eSuperTypes="#//DAbstractSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="DInstantiableSection" eSuperTypes="#//DAbstractSection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bContent" lowerBound="1"
        upperBound="-1" eType="#//DBodyContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBodyContent" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DParagraph" eSuperTypes="#//DBodyContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pContent" lowerBound="1"
        upperBound="-1" eType="#//DParagraphContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DParagraphContent" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DRun" eSuperTypes="#//DParagraphContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" lowerBound="1" eType="#//DText"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//DRunFormat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DRunFormat">
    <eLiterals name="bold"/>
    <eLiterals name="italic" value="1"/>
    <eLiterals name="underscore" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DHyperlink" eSuperTypes="#//DParagraphContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="run" lowerBound="1" eType="#//DRun"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//DReferenceableObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DReferenceableObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="DListContent" abstract="true" eSuperTypes="#//DBodyContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" upperBound="-1"
        eType="#//DListItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DListItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="paragraph" lowerBound="1"
        upperBound="-1" eType="#//DParagraph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sublist" eType="#//DListContent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DItemize" eSuperTypes="#//DListContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="DEnumerate" eSuperTypes="#//DListContent"/>
</ecore:EPackage>
