<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="doctpl" nsURI="http://srg.aut.uah.es/micobs/doctpl/doctpl" nsPrefix="micobs.doctpl">
  <eClassifiers xsi:type="ecore:EClass" name="DDocumentTemplate" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocuments" upperBound="-1"
        eType="#//DApplicableDocument" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocuments" upperBound="-1"
        eType="#//DReferenceDocument" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="figures" upperBound="-1"
        eType="#//DAbstractFigure" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//DAbstractTable" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//DAbstractSection" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paragraphs" upperBound="-1"
        eType="#//DParagraph" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractRelatedDocument" abstract="true"
      eSuperTypes="#//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DApplicableDocument" eSuperTypes="#//DAbstractRelatedDocument"/>
  <eClassifiers xsi:type="ecore:EClass" name="DReferenceDocument" eSuperTypes="#//DAbstractRelatedDocument"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractFigure" abstract="true" eSuperTypes="#//DBodyContent #//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DFigureFromFile" eSuperTypes="#//DAbstractFigure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceFile" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractTable" abstract="true" eSuperTypes="#//DBodyContent #//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTableFromFile" eSuperTypes="#//DAbstractTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceFile" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBasicTable" eSuperTypes="#//DAbstractTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" lowerBound="1" upperBound="-1"
        eType="#//DRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" lowerBound="1" upperBound="-1"
        eType="#//DCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DCell" eSuperTypes="#//DBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colSpan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowSpan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shadow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAbstractSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsections" upperBound="-1"
        eType="#//DAbstractSection" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DFixedSection" eSuperTypes="#//DAbstractSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="DInstantiableSection" eSuperTypes="#//DAbstractSection ../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj"/>
  <eClassifiers xsi:type="ecore:EClass" name="DBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyContent" lowerBound="1"
        upperBound="-1" eType="#//DBodyContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBodyContent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="#//DAlignment"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DAlignment">
    <eLiterals name="left" literal="left"/>
    <eLiterals name="center" value="1" literal="center"/>
    <eLiterals name="right" value="2" literal="right"/>
    <eLiterals name="justified" value="3" literal="justified"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DParagraph" eSuperTypes="#//DBodyContent #//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="paragraphContent" lowerBound="1"
        upperBound="-1" eType="#//DParagraphContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DParagraphContent" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DRunAttributes">
    <eLiterals name="FALSE" literal="false"/>
    <eLiterals name="TRUE" value="1" literal="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DRun" eSuperTypes="#//DParagraphContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="#//DRunAttributes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italics" eType="#//DRunAttributes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="underline" eType="#//DRunAttributes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tab" eType="#//DTab" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" lowerBound="1" eType="#//DText"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTab"/>
  <eClassifiers xsi:type="ecore:EClass" name="DText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DHyperlink" eSuperTypes="#//DParagraphContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="run" eType="#//DRun" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//DReferenceableObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DListContent" abstract="true" eSuperTypes="#//DBodyContent #//DReferenceableObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" upperBound="-1"
        eType="#//DListItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DListItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="paragraph" eType="#//DParagraph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sublist" eType="#//DListContent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DItemize" eSuperTypes="#//DListContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="DEnumerate" eSuperTypes="#//DListContent"/>
</ecore:EPackage>
