<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="doc" nsURI="http://srg.aut.uah.es/micobs/doc/doc" nsPrefix="micobs.doc">
  <eClassifiers xsi:type="ecore:EClass" name="DDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" upperBound="-1"
        eType="#//DDSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DDSection" eSuperTypes="#//DDSectionContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sectionContent" upperBound="-1"
        eType="#//DDSectionContent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DDSectionContent" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DDBody" eSuperTypes="#//DDSectionContent ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DBody"/>
</ecore:EPackage>
